# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#User.create(
#    name: "Evan Hildreth",
#    email: "me@eph.me",
#    uid: "1427716",
#    provider: "github",
#    is_admin: true
#)

Region.create(name: 'Birmingham-Anniston-Tuscaloosa')
Region.create(name: 'Dothan')
Region.create(name: 'Huntsville-Decatur-Florence')
Region.create(name: 'Montgomery-Selma')
Region.create(name: 'Anchorage')
Region.create(name: 'Fairbanks')
Region.create(name: 'Juneau')
#Region.create(name: 'Phoenix')
Region.create(name: 'Tucson-Sierra Vista')
Region.create(name: 'Fort Smith-Fayetteville-Springdale-Rogers')
Region.create(name: 'Jonesboro')
Region.create(name: 'Little Rock-Pine Bluff')
Region.create(name: 'Chico-Redding')
Region.create(name: 'Eureka')
#Region.create(name: 'Fresno-Visalia')
#Region.create(name: 'Los Angeles')
Region.create(name: 'Monterey-Salinas')
Region.create(name: 'Palm Springs')
Region.create(name: 'Sacramento-Stockton-Modesto')
Region.create(name: 'San Diego')
#Region.create(name: 'San Francisco-Oakland-San Jose')
Region.create(name: 'Santa Barbara-Santa Maria-San Luis Obispo-Bakersfield')
Region.create(name: 'Yuma-El Centro')
Region.create(name: 'Colorado Springs-Pueblo')
Region.create(name: 'Denver')
Region.create(name: 'Grand Junction-Montrose')
Region.create(name: 'Hartford-New Haven')
#Region.create(name: 'District of Columbia')
Region.create(name: 'Fort Myers-Naples')
#Region.create(name: 'Gainesville')
Region.create(name: 'Jacksonville-Brunswick')
#Region.create(name: 'Miami-Fort Lauderdale')
Region.create(name: 'Mobile-Pensacola')
#Region.create(name: 'Orlando-Daytona Beach-Melbourne')
Region.create(name: 'Panama City')
Region.create(name: 'Tallahassee-Thomasville')
#Region.create(name: 'Tampa-St. Petersburg-Sarasota')
Region.create(name: 'West Palm Beach-Fort Pierce')
Region.create(name: 'Albany')
#Region.create(name: 'Atlanta')
Region.create(name: 'Augusta')
Region.create(name: 'Columbus')
Region.create(name: 'Macon')
Region.create(name: 'Savannah')
Region.create(name: 'Guam')
Region.create(name: 'Honolulu')
Region.create(name: 'Boise')
Region.create(name: 'Idaho Falls-Pocatello')
Region.create(name: 'Twin Falls')
Region.create(name: 'Champaign-Springfield-Decatur')
#Region.create(name: 'Chicago')
Region.create(name: 'Peoria-Bloomington')
Region.create(name: 'Quincy-Hannibal-Keokuk')
Region.create(name: 'Rockford')
Region.create(name: 'Evansville')
Region.create(name: 'Fort Wayne')
Region.create(name: 'Indianapolis')
Region.create(name: 'Lafayette, IN')
Region.create(name: 'South Bend-Elkhart-Benton Harbor')
Region.create(name: 'Terre Haute')
Region.create(name: 'Cedar Rapids-Waterloo-Dubuque')
Region.create(name: 'Davenport-Rock Island-Moline')
Region.create(name: 'Des Moines-Ames')
Region.create(name: 'Ottumwa-Kirksville')
Region.create(name: 'Sioux City')
Region.create(name: 'Joplin-Pittsburg')
Region.create(name: 'Topeka')
Region.create(name: 'Wichita-Hutchinson')
Region.create(name: 'Bowling Green')
Region.create(name: 'Lexington')
Region.create(name: 'Louisville')
Region.create(name: 'Alexandria')
Region.create(name: 'Baton Rouge')
Region.create(name: 'Lafayette, LA')
Region.create(name: 'Lake Charles')
Region.create(name: 'Monroe-El Dorado')
Region.create(name: 'New Orleans')
Region.create(name: 'Shreveport')
Region.create(name: 'Bangor')
Region.create(name: 'Portland-Auburn')
Region.create(name: 'Presque Isle')
Region.create(name: 'Baltimore')
Region.create(name: 'Salisbury')
Region.create(name: 'Boston-Manchester')
Region.create(name: 'Springfield-Holyoke')
Region.create(name: 'Alpena')
#Region.create(name: 'Detroit')
Region.create(name: 'Flint-Saginaw-Bay City')
Region.create(name: 'Grand Rapids-Kalamazoo-Battle Creek')
Region.create(name: 'Lansing')
Region.create(name: 'Marquette')
Region.create(name: 'Traverse City-Cadillac')
Region.create(name: 'Duluth-Superior')
Region.create(name: 'Mankato')
#Region.create(name: 'Minneapolis–Saint Paul')
Region.create(name: 'Rochester-Mason City-Austin')
Region.create(name: 'Biloxi-Gulfport')
Region.create(name: 'Columbus-Tupelo-West Point')
Region.create(name: 'Greenwood-Greenville')
Region.create(name: 'Hattiesburg-Laurel')
Region.create(name: 'Jackson, MI')
Region.create(name: 'Meridian')
Region.create(name: 'Columbia-Jefferson City')
Region.create(name: 'Kansas City')
Region.create(name: 'Paducah-Cape Girardeau-Marion-Carbondale-McLeansboro-Poplar Bluff-Mount Vernon')
Region.create(name: 'Springfield')
Region.create(name: 'St. Joseph')
Region.create(name: 'St. Louis')
Region.create(name: 'Billings')
Region.create(name: 'Butte-Bozeman')
Region.create(name: 'Glendive')
Region.create(name: 'Great Falls')
Region.create(name: 'Helena')
Region.create(name: 'Missoula')
Region.create(name: 'Lincoln-Hastings-Kearney')
Region.create(name: 'North Platte')
Region.create(name: 'Omaha')
Region.create(name: 'Las Vegas')
Region.create(name: 'Reno')
Region.create(name: 'Albuquerque-Santa Fe')
Region.create(name: 'Albany-Schenectady-Troy')
Region.create(name: 'Binghamton')
Region.create(name: 'Buffalo')
Region.create(name: 'Burlington-Plattsburgh')
Region.create(name: 'Elmira')
#Region.create(name: 'New York City')
Region.create(name: 'Rochester')
Region.create(name: 'Syracuse')
Region.create(name: 'Utica')
Region.create(name: 'Watertown')
#Region.create(name: 'Charlotte')
Region.create(name: 'Greensboro-High Point-Winston-Salem')
Region.create(name: 'Greenville-New Bern-Washington')
#Region.create(name: 'Raleigh-Durham-Fayetteville')
Region.create(name: 'Wilmington')
Region.create(name: 'Fargo-Valley City')
Region.create(name: 'Minot-Bismarck-Dickinson')
Region.create(name: 'Cincinnati')
Region.create(name: 'Cleveland-Akron-Canton')
Region.create(name: 'Columbus-Zanesville')
Region.create(name: 'Dayton')
Region.create(name: 'Lima')
Region.create(name: 'Toledo')
Region.create(name: 'Youngstown')
Region.create(name: 'Oklahoma City')
Region.create(name: 'Sherman-Ada')
Region.create(name: 'Tulsa')
Region.create(name: 'Eugene-Bend')
Region.create(name: 'Medford-Klamath Falls')
Region.create(name: 'Portland')
Region.create(name: 'Erie')
Region.create(name: 'Harrisburg-Lancaster-Lebanon-York')
Region.create(name: 'Johnstown-Altoona')
#Region.create(name: 'Philadelphia')
Region.create(name: 'Pittsburgh')
Region.create(name: 'Wilkes-Barre-Scranton')
Region.create(name: 'Providence-New Bedford')
Region.create(name: 'Charleston')
Region.create(name: 'Columbia')
Region.create(name: 'Greenville-Spartanburg-Asheville-Anderson')
Region.create(name: 'Myrtle Beach-Florence')
Region.create(name: 'Rapid City')
Region.create(name: 'Mitchell-Sioux Falls')
Region.create(name: 'Chattanooga')
Region.create(name: 'Jackson, TN')
Region.create(name: 'Knoxville')
Region.create(name: 'Memphis')
Region.create(name: 'Nashville')
Region.create(name: 'Tri-Cities')
Region.create(name: 'Abilene-Sweetwater')
Region.create(name: 'Amarillo')
#Region.create(name: 'Austin')
Region.create(name: 'Beaumont-Port Arthur')
Region.create(name: 'Corpus Christi-Victoria')
#Region.create(name: 'Dallas-Fort Worth')
Region.create(name: 'El Paso')
Region.create(name: 'Harlingen-McAllen-Brownsville')
Region.create(name: 'Houston')
Region.create(name: 'Laredo')
Region.create(name: 'Lubbock')
Region.create(name: 'Odessa-Midland')
Region.create(name: 'San Angelo')
Region.create(name: 'San Antonio')
Region.create(name: 'Tyler-Lufkin-Longview-Nacogdoches')
Region.create(name: 'Waco-Temple-Bryan')
Region.create(name: 'Wichita Falls-Lawton')
Region.create(name: 'Salt Lake City')
Region.create(name: 'Charlottesville')
Region.create(name: 'Harrisonburg')
Region.create(name: 'Norfolk-Portsmouth-Newport News')
Region.create(name: 'Richmond-Petersburg')
Region.create(name: 'Roanoke-Lynchburg')
Region.create(name: 'Seattle-Tacoma')
Region.create(name: 'Spokane')
Region.create(name: 'Yakima-Pasco-Richland-Kennewick')
Region.create(name: 'Bluefield-Beckley-Oak Hill')
Region.create(name: 'Charleston-Huntington')
Region.create(name: 'Clarksburg-Weston')
Region.create(name: 'Parkersburg')
Region.create(name: 'Wheeling-Steubenville')
Region.create(name: 'Green Bay-Appleton')
Region.create(name: 'La Crosse-Eau Claire')
Region.create(name: 'Madison')
Region.create(name: 'Milwaukee')
Region.create(name: 'Wausau-Rhinelander')
Region.create(name: 'Casper-Riverton')
Region.create(name: 'Cheyenne-Scottsbluff')
Region.create(name: 'Puerto Rico')